package com.ebookfrenzy.mad155_recyclerandcardview.adapters

import android.content.Context
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.ImageView
import android.widget.TextView
import android.widget.Toast
import androidx.recyclerview.widget.RecyclerView
import com.ebookfrenzy.mad155_recyclerandcardview.R
import com.ebookfrenzy.mad155_recyclerandcardview.models.MyModel

class MyAdapter(var context: Context, var arrayList: ArrayList<MyModel>):
    RecyclerView.Adapter<MyAdapter.ItemHolder>(){


    class ItemHolder(itemView: View):RecyclerView.ViewHolder(itemView){
        var icons = itemView.findViewById<ImageView>(R.id.icon_image)
        var txt = itemView.findViewById<TextView>(R.id.txtTitle)
    }

    // these functions were generated by class:MyAdapter>RightClick>AddMembers>[add all three]
    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ItemHolder {
        val itemholder = LayoutInflater.from(parent.context).
            inflate(R.layout.grid_view, parent, false)// this basicly intializes the view to be viewed.. I think..
        return ItemHolder(itemholder)
    }

    override fun onBindViewHolder(holder: ItemHolder, position: Int) {
        var myCard: MyModel = arrayList.get(position)
        holder.icons.setImageResource(myCard.iconCard!!)
        holder.txt.text = myCard.textCard
        
        holder.txt.setOnClickListener {
            Toast.makeText(context, myCard.textCard, Toast.LENGTH_SHORT).show()
        }

    }

    override fun getItemCount(): Int {
        return arrayList.size // this is just looking to return the array size
    }


}